### ISSUE TITLE
Question about theme

### ISSUE THREAD

**Issue by BigFlubba** [maenDisease/Float#1]
To save the headache if not, is this theme compatible and written to accommodate other themes? My main theme is AMOLED-cord and with minimal mode enabled can all 3 of these themes work fluently. Minimal mode and AMOLED-cord work well, but what happens with a 3rd theme, I have no idea.

**Comment by maenDisease** [comment]
Testing AMOLED-cord with Float works fine, since Float uses MinimalMode, it shouldn't have any issues, you can preview it here [Gibbu theme preview](https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/maenDisease/Float/Float.theme.css|https://luckfire.github.io/amoled-cord/src/support/AMOLED-Cord.theme.css|https://cdn.jsdelivr.net/gh/SmolAlli/Themes/MinimalMode/MinimalMode.theme.css)

**Comment by BigFlubba** [comment]
Nice
